Employee_accounts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = (
    # urls for Employee
    url(r'^employee/$', views.EmployeeListView.as_view(), name='Employee_accounts_employee_list'),
   )

#which means we can append more urls that can be specific to any apps
urlpatterns += (
    # urls for Employee
    url(r'^list/$', views.EmployeeListView.as_view(), name='Employee_accounts_employee_list'),
    #url(r'^employee/list/$', views.employeelistview, name='employeelistview'),
    #class createview
    url(r'^employee/cb/create/$', views.EmployeeCreateView.as_view(), name='Employee_accounts_employee_create'),
    #func createview
    url(r'^employee/fb/create/$', views.employeecreateview, name='employeecreateview'),

    url(r'^cb/detail/(?P<pk>[0-9]+)/$', views.EmployeeDetailView.as_view(), name='Employee_accounts_employee_detail'),
    url(r'^fb/detail/(?P<pk>[0-9]+)/$', views.employeeDetailView, name='employeeDetailView'),

    url(r'^update/(?P<slug>\S+)/$', views.EmployeeUpdateView.as_view(), name='Employee_accounts_employee_update'),
)

testroom/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forms_test/', include('forms_test.urls', namespace='forms_test')),
    url(r'^overriding/', include('overriding.urls', namespace='overriding')),
    url(r'^accounts/', include('Employee_accounts.urls', namespace='accounts')),
    url(r'^miscellaneous/', include('miscellaneous.urls', namespace='miscellaneous')),
]

Employee_accounts/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields


class Employee(models.Model):

    f_name = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=False)
    website = models.URLField(max_length=50, null=True)
    address = models.CharField(max_length=255, null=False)
    about = models.TextField(max_length=500, null=False)
    slug = extension_fields.AutoSlugField(unique=True, populate_from='f_name')
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('accounts:Employee_accounts_employee_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('accounts:Employee_accounts_employee_update', args=(self.slug,))



#creating subclass(Developer) that inherits from parent class(Employee)
# class Developer(Employee):
# we can have normal class topics in this as this is models.py and only database models are suppose to be here.
#we are going to create a seprate package to test classes and methods in them and how to inherit from a class and override any of it's behaviour

Employee_accounts/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['f_name', 'l_name']

Employee_accounts/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Employee
from .forms import EmployeeForm
from django.shortcuts import render, HttpResponse, redirect, reverse


class EmployeeListView(ListView):
    model = Employee
    template_name = 'Employee_accounts/employee_list_func.html'
    context_object_name = 'all_emp'

#list function view
def employeelistview(request):
    all_emp = Employee.objects.all()
    return render(request, template_name='Employee_accounts/employee_list.html', context={'object_list':all_emp})

class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm

#create function view
def employeecreateview(request):
    if request.method =='GET':
        form = EmployeeForm()
        return render(request, template_name='Employee_accounts/employee_form.html', context={'form': form})

    if request.method =='POST':
        form = EmployeeForm(request.POST)
        form.save()
        return redirect(reverse('accounts:Employee_accounts_employee_list'))

class EmployeeDetailView(DetailView):
    model = Employee

#Employee
def employeeDetailView(request, pk):
    emp = Employee.objects.get(pk=pk)
    template_name = 'Employee_accounts/employee_detail.html'
    return render(request, template_name=template_name, context={'emp':emp})


class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm


#ListView, TemplateView, CreateView, UpdateView, DeleteView

Employee_accounts/templates/Employee_accounts/employee_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ emp.f_name }} {{ emp.l_name }}</td></tr>
<tr><td>slug</td><td>{{ emp.slug }}</td></tr>
<tr><td>created</td><td>{{ emp.created }}</td></tr>
<tr><td>last_updated</td><td>{{ emp.last_updated }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Employee</a>

{% endblock %}

Employee_accounts/templates/Employee_accounts/employee_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<form method="post">
{% csrf_token %}
{{form}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
<h1>All Employees</h1>
All Emp objs: {{ emps }}
{% endblock %}

Employee_accounts/templates/Employee_accounts/employee_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr>
    <td>name</td>
    <td>slug</td>
    <td>created</td>
    <td>last_updated</td>
</tr>

{% if object_list %}
    {% for object in object_list %}
    <tr>
        <td><a href="{{object.get_absolute_url}}">{{ object.name }}</a></td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    {% endfor %}
{% endif %}
</table><a class="btn btn-primary" href="{% url 'accounts:Employee_accounts_employee_create' %}">Create new Employee</a>
{% endblock %}

Employee_accounts/templates/Employee_accounts/employee_list_func.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>template_name in class worked!!</h2>
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr>
    <td>name</td>
    <td>slug</td>
    <td>created</td>
    <td>last_updated</td>
</tr>

{% if object_list %}
    {% for object in all_emp %}
    <tr>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.name }}</td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    {% endfor %}
{% endif %}
</table><a class="btn btn-primary" href="{% url 'accounts:Employee_accounts_employee_create' %}">Create new Employee</a>
{% endblock %}