forms_test/urls.py
from django.conf.urls import url, include
from rest_framework import routers #what is this for
from . import views


urlpatterns = (
    # urls for Author
    url(r'^author/cb/list/$', views.AuthorListView.as_view(), name='forms_test_author_list'),
    url(r'^author/fb/list/$', views.authorListView, name='authorListView'),
    url(r'^post/cb/list/$', views.PostListView.as_view(), name='PostListView'),
    url(r'^post/cb/protected_list/$', views.Protected_post_list, name='protected_post_list'),

    url(r'^author/cb/create/$', views.AuthorCreateView.as_view(), name='forms_test_author_create'),
    # url(r'^author/fb/create/$', views.authorCreateView, name='authorCreateView'),

    url(r'^author/cb/detail/(?P<pk>\S+)/$', views.AuthorDetailView.as_view(), name='forms_test_author_detail'),
    url(r'^author/fb/detail/(?P<pk>[0-9]+)/$', views.authorDetailView, name='authorDetailView'),

    #url(r'^author/p_detailView/(?P<pk>\S+)/$', views.ProtectedDetailView, name='ProtectedDetailView'),
    url(r'^author/update/(?P<pk>\S+)/$', views.AuthorUpdateView.as_view(), name='forms_test_author_update'),
    url(r'^form/unbound/', views.unbound_form, name='unbound_form'),
    url(r'^form/bound/', views.bound_form, name='bound_form'),
    #url(r'^form/basic/', views.home_basic_form, name='home_basic_form'),
    url(r'^form/cb/basic/', views.HomeView.as_view(), name='home_basic_form'),


)

testroom/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forms_test/', include('forms_test.urls', namespace='forms_test')),
    url(r'^overriding/', include('overriding.urls', namespace='overriding')),
    url(r'^accounts/', include('Employee_accounts.urls', namespace='accounts')),
    url(r'^miscellaneous/', include('miscellaneous.urls', namespace='miscellaneous')),
]

forms_test/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.db import models as models
from django_extensions.db import fields as extension_fields
from .my_managers import ActiveAuthorManager

#we use model Manager to override some or any of the method or value of attribute that exists in Manager class

class Author(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=100, blank=True)
    address = models.CharField(max_length=300)
    desc = models.CharField(max_length=500)
    active = models.BooleanField(default=False)
    objects = ActiveAuthorManager()

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('forms_test:forms_test_author_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('forms_test:forms_test_author_update', args=(self.pk,))


class Form_Data(models.Model):

    # Fields
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('forms_test:home_form')

    def get_update_url(self):
        return reverse('forms_test:home_form')


class Post(models.Model):
    post = models.CharField(max_length=255)
    created_date = models.DateField(auto_now=False, auto_now_add=True, editable=False)
    last_updated = models.DateField(auto_now=True, auto_now_add=False, editable=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


    class Meta:
        ordering = ('-pk',)

    # def __str__(self):
    #     return u'%s' % self.name
    #
    # def get_absolute_url(self):
    #     return reverse('forms_test:home_form')
    #
    # def get_update_url(self):
    #     return reverse('forms_test:home_form')
    #

forms_test/forms.py
from django import forms
from .models import Author, Post


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'phone', 'email', 'address', 'desc']


class UnboundForm(forms.Form):
    name = forms.CharField()

class PostunboundForm(forms.Form):
    post = forms.CharField()


class PostboundForm(forms.ModelForm):
    post = forms.CharField()
    class Meta:
        model = Post
        fields = ('post',)


class boundForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

forms_test/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView, TemplateView
from .models import Author, Post
from .forms import AuthorForm
from django.shortcuts import render, redirect, reverse
from .models import Form_Data
from .forms import UnboundForm, boundForm, PostboundForm
# from overriding.views import OwnedObjectMixin
from django.contrib import messages
from django.shortcuts import Http404, HttpResponse


class OwnedObjectMixin(object):
    def get_queryset(self, *args, **kwargs):
        if not obj.user == self.request.user:
            raise Http404

        return self.get_queryset().filter(active=True)

        return obj


class PostListView(ListView):
    model = Post


class Protected_post_list(OwnedObjectMixin, ListView):
    model = Author


































def home_basic_form(request): #i am unable to display the data
    if request.method == 'GET':
        messages.success(request, 'fill up this form!')
        return render(request, 'forms_test/home.html')
    else:
        #WHAT IF WE WANT TO SAVE DATA IN DATABASE
        form_data = Form_Data()
        form_data.name = request.POST['form_data']
        form_data.save()
        messages.success(request, 'YOur data is successfully saved!')
        objs = Form_Data.objects.all
        context = {'name': request.POST['form_data'], 'objs': objs}
        return render(request, 'forms_test/home.html', context=context)

class HomeView(TemplateView):
    template_name = 'forms_test/home.html'

    def get(self, request, *args, **kwargs):#def get(self, request, *args, **kwargs):
        template_name = 'forms_test/PostunboundForm.html'
        form = PostboundForm()
        posts = Post.objects.all()
        print(posts)
        return render(request, template_name=template_name, context={'form': form, 'posts': posts})

    def post(self, request, *args, **kwargs):#def get(self, request, *args, **kwargs):
        template_name = 'forms_test/PostunboundForm.html'
        form = PostboundForm(request.POST)
        if form.is_valid():
            print(request.user)
            post_obj = form.save(commit=False) #it returns the post object
            post_obj.author = request.user
            post_obj.save()
            form = PostboundForm()
        return render(request, template_name=template_name, context={'form':form})

            # return redirect(reverse('forms_test:forms_test_author_list'))
            # return redirect('/forms_test/author/cb/list/')



class AuthorListView(ListView):
    model = Author

    # < --> by default
    #context_= Author.objects.get_queryset()
    #template_name = 'forms_test/author_list.html'
    #self.object_list = self.get_queryset()


#function based views
def authorListView(request):
    template_name = 'forms_test/author_list.html'
    context = {'object_list': Author.objects.get_queryset()}
    return render(request, template_name=template_name, context=context)





class AuthorDetailView(DetailView):
    model = Author

def authorDetailView(request, pk):
    author = Author.objects.get(pk=pk)
    template_name = 'forms_test/author_detail.html'
    context = {'object': author}
    return render(request, template_name=template_name, context=context)


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm


class ProtectedDetailView(DetailView):
    model = Author


#FORM HANDLING VIEWS
#can we handle this in a class

def unbound_form(request): #i am unable to display the data
    if request.method == 'GET':
        form = UnboundForm()
        context = {'form': form}
        return render(request, 'forms_test/unbound_form.html', context=context)
    else:
        form = UnboundForm()
        print(request.POST)
        author = Author()
        author.name = request.POST
        author.save()
        print(Author.objects.all())
        context = {'form': form, 'name': request.POST}
        return render(request, 'forms_test/unbound_form.html', context=context)

def bound_form(request): #i am unable to display the data
    if request.method == 'GET':
        form = boundForm()
        context = {'form': form}
        return render(request, 'forms_test/bound_form.html', context=context)
    else:
        form = boundForm(request.POST)
        # author = Form_Data()
        if form.is_valid():
            form_data = form.save(commit=False)
            form_data.user = request.user
            form_data.save()
            # text = form.cleaned_data['post']
            # form = boundForm()
        return redirect('/forms_test/form/cb/basic/')#('/forms_test/form/basic/')
        #     # args = {'form': form, 'text': text}
        #     # author.name = name
        #     # author.save()
        # context = {'objs':Author.objects.all()}
        # return render(request, 'forms_test/bound_form.html', context=context)
        #

forms_test/templates/forms_test/PostunboundForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PostunboundForm</title>
</head>
<body>
<h2>PostunboundForm</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
    {{ text }}
    {% for post in posts %}
        <h3>{{ post.post }}</h3>  <--posted on:{{ post.created_date }} By {{ post.author }}<br>
    {% endfor %}

</body>
</html>

forms_test/templates/forms_test/author_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'forms_test:forms_test_author_list' %}">Author Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>phone</td><td>{{ object.phone }}</td></tr>
<tr><td>email</td><td>{{ object.email }}</td></tr>
<tr><td>address</td><td>{{ object.address }}</td></tr>
<tr><td>desc</td><td>{{ object.desc }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Author</a>

{% endblock %}

forms_test/templates/forms_test/author_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'forms_test:forms_test_author_list' %}">Author Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

forms_test/templates/forms_test/author_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="">Author Listing</a></p>
<table class="table">
    <tr>
    <td>ID</td><td>Link</td>
        <td>name</td>
        <td>phone</td>
        <td>email</td>
        <td>address</td>
        <td>desc</td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.name }}</td>
        <td>{{ object.phone }}</td>
        <td>{{ object.email }}</td>
        <td>{{ object.address }}</td>
        <td>{{ object.desc }}</td>
    </tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'forms_test:forms_test_author_create' %}">Create new Author</a>

{% endblock %}

forms_test/templates/forms_test/bound_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bound_form</title>
</head>
<body>

<form action="" method="post">{% csrf_token %}
    {{ form }}
<button type="submit">Submit this Form!</button>
</form>
    {{ text }}
    {% for post in posts %}
        <h3>{{ post.post }}</h3>  <--posted on:{{ post.created_date }} By {{ post.author }}<br>
    {% endfor %}

</body>
</html>

forms_test/templates/forms_test/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home_Form</title>
</head>
<body>
<h2>This is the first basic form</h2>

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

<ol>
    <li>
        <p>We need to play with it's data on page</p>
    </li>
    <li>
        <p>and if possible we will try to add it to the database</p>
    </li>
</ol>
<form action="" method="post" >{% csrf_token %}
    <input type="text" placeholder="type your name..." name="form_data">
    <button type="submit">Submit this form</button>
    <h3>Hello {{ name }} welcome to Equevix form learning</h3>
    <h2>SO WE ARE SUCCESSFULLY ABLE TO SAVE THE DATA IN DB</h2>
</form>
whole_form_data_objs: {{ objs }}
</body>
</html>

forms_test/templates/forms_test/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post_list</title>
</head>
<body>
<h2>post_list</h2>
</body>
</html>

forms_test/templates/forms_test/unbound_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>unbound_form</title>
</head>
<body>
{{ form }}
<button type="submit">Submit this Form!</button>
</body>
</html>